//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marathon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marathon
    {
        public int MarathonId { get; set; }
        public string MarathonName { get; set; }
        public string CityName { get; set; }
        public int CountryCode { get; set; }
        public string YearHeld { get; set; }
    }
}
